export interface Article {
  title: string
  description: string
  slug: string
  category: string
  readTime: string
  image?: string
}

export const articles: Article[] = [
  {
    title: 'The Complete Garage Guide 2026: Every System, Every Decision, Every Cost',
    description: 'The complete reference guide to your garage covering structure and fire separation, the garage door system, flooring, heating and cooling, lighting, storage and organization, electrical and EV charging, safety and ventilation, and maintenance.',
    slug: 'guides/complete-garage-guide',
    category: 'Guide',
    readTime: '22 min read',
    image: '/images/garageguide complete.jpg',
  },
  {
        title: 'The Complete Garage Organization Guide 2026: Zones, Systems, and Step-by-Step Plans',
    description: 'Transform your garage from a cluttered mess into an organized, functional space. Complete guide to storage systems, shelving, ceiling racks, and layout planning.',
        slug: 'guides/complete-garage-organization-guide',
    category: 'Guide',
    readTime: '25 min read',
    image: '/images/organized garage.jpg',
  },
  {
    title: 'Garage Floor Coating Cost 2026: Epoxy, Polyurea, and More',
    description: 'Garage floor coating costs $3 to $12 per square foot installed. Compare epoxy, polyurea, polyaspartic, and DIY options with real pricing and pros and cons.',
    slug: 'cost-guides/garage-floor-coating-cost',
    category: 'Cost Guide',
    readTime: '20 min read',
    image: '/images/garagefloorcoating.jpg',
  },
  {
    title: 'Cost to Build a Garage in 2026: Every Size, Every Type, Every Factor',
    description: 'Building a garage costs $18,000 to $70,000 for most residential projects in 2026. Covers attached and detached garages by size, cost per square foot breakdown, permits, prefab vs. stick-built, and the 10 factors that move the price.',
    slug: 'cost-guides/garage-addition-cost',
    category: 'Cost Guide',
    readTime: '15 min read',
    image: '/images/garage cost guide.jpg',
  },
  {
    title: 'Best Garage Storage Systems 2026: Wall, Ceiling, and Cabinet Options',
    description: 'We reviewed the top garage storage systems including wall-mounted tracks, overhead ceiling racks, and modular cabinets. See which ones are worth the investment.',
    slug: 'reviews/best-garage-storage-systems',
    category: 'Review',
    readTime: '22 min read',
    image: '/images/organized garage.jpg',
  },
  {
    title: 'How to Insulate Your Garage: Complete DIY Guide',
    description: 'Insulating your garage costs $1 to $3 per square foot for walls and $2 to $5 for the garage door. Learn which insulation type works best and how to install it yourself.',
    slug: 'guides/how-to-insulate-garage',
    category: 'Guide',
    readTime: '20 min read',
    image: '/images/insulate garage.jpg',
  },
  {
    title: 'Garage Door Opener Not Working? Troubleshooting Guide',
    description: 'Diagnose and fix common garage door opener problems including remote failures, sensor issues, grinding noises, and doors that reverse. Step-by-step troubleshooting.',
    slug: 'problems/garage-door-opener-not-working',
    category: 'Problem',
    readTime: '18 min read',
    image: '/images/garagedoornotworking.jpg',
  },
  {
    title: 'Best Garage Floor Epoxy Kits 2026: DIY Picks That Actually Last',
    description: 'The best DIY garage floor epoxy kit for most homeowners is the Rust-Oleum RockSolid Polycuramine ($200 to $280). We tested and ranked 5 kits by durability, ease of use, and value.',
    slug: 'reviews/best-garage-floor-epoxy',
    category: 'Review',
    readTime: '20 min read',
    image: '/images/epoxy kits.jpg',
  },
  {
    title: 'Garage Heater Guide: Best Ways to Heat Your Garage',
    description: 'Compare forced air, infrared, mini-split, and portable garage heaters. Costs, BTU requirements by garage size, installation, and which type works best for your setup.',
    slug: 'guides/garage-heater-guide',
    category: 'Guide',
    readTime: '22 min read',
    image: '/images/garageheater.jpg',
  },
  {
    title: 'Garage Ventilation Guide: Carbon Monoxide Safety, CFM Calculations, and the Right Fan for Every Garage',
    description: 'The complete garage ventilation guide covering carbon monoxide safety, CFM calculations for residential garages, exhaust fan selection, workshop ventilation requirements, CO detector placement, building code requirements, and ventilation solutions for every garage type.',
    slug: 'guides/garage-ventilation-guide',
    category: 'Guide',
    readTime: '14 min read',
    image: '/images/garage-ventilation-guide.jpg',
  },
  {
    title: 'Water Leaking Into Garage: Causes, Fixes, and Prevention',
    description: 'Water in your garage can come from the door seal, floor cracks, walls, or poor drainage. Learn the 6 most common causes and how to fix each one permanently.',
    slug: 'problems/water-leaking-into-garage',
    category: 'Problem',
    readTime: '18 min read',
        image: '/images/garage leak .jpg',
  },
  {
    title: 'Best Garage Lighting 2026: LED Options for Every Budget',
    description: 'The best garage lighting delivers 50+ lumens per square foot. We tested LED shop lights, wraparound fixtures, and panel lights to find the best options.',
    slug: 'reviews/best-garage-lighting',
    category: 'Review',
    readTime: '18 min read',
    image: '/images/bestgaragelighting.jpg',
  },
  {
    title: 'Garage Door Replacement Cost 2026: Complete Price Guide',
    description: 'A new garage door costs $800 to $4,000 installed. Complete pricing by material, style, size, and opener type plus how to save money on installation.',
    slug: 'cost-guides/garage-door-replacement-cost',
    category: 'Cost Guide',
    readTime: '20 min read',
    image: '/images/garagedoornotworking.jpg',
  },
  {
    title: 'Best Garage Door Openers 2026: Tested Picks for Every Garage',
    description: 'The best garage door opener for most homeowners is a belt-drive model with WiFi and battery backup in the $200 to $400 range. We tested top picks from Chamberlain, Genie, and LiftMaster.',
    slug: 'reviews/best-garage-door-openers',
    category: 'Review',
    readTime: '22 min read',
    image: '/images/garageopeners.jpg',
    },
    {
    title: 'Best Garage Heaters 2026: Top Picks for Every Budget and Garage Size',
    description: 'The best garage heater for most homeowners is a 240V electric forced-air unit in the $200 to $300 range. We reviewed 7 heaters across electric, propane, natural gas, and mini-split categories.',
    slug: 'reviews/best-garage-heaters',
    category: 'Review',
    readTime: '25 min read',
    image: '/images/garageheaters.jpg',
  },
  {
    title: 'Epoxy Garage Floor Cost 2026: DIY vs Professional',
    description: 'A professionally installed epoxy garage floor costs $3 to $12 per square foot, or $1,500 to $5,000 for a standard two-car garage. DIY kits cost $100 to $300 but last 2 to 5 years vs 10 to 20 years for professional installation.',
    slug: 'cost-guides/epoxy-garage-floor-cost',
    category: 'Cost Guide',
    readTime: '22 min read',
    image: '/images/Epoxy Garage Floor Cost.jpg',
  },
    {
    title: 'Attached vs Detached Garage: Cost, Pros, Cons, and Resale Value 2026',
    description: 'An attached garage costs $20,000 to $40,000. A detached garage costs $25,000 to $55,000. Compare fire safety, air quality, noise, convenience, and resale value.',
    slug: 'comparisons/attached-vs-detached-garage',
    category: 'Comparison',
    readTime: '25 min read',
    image: '/images/detatchedgarage.jpg',
  },
  {
    title: 'Garage Conversion Cost 2026: Turn Your Garage Into Living Space',
    description: 'A garage conversion costs $6,000 to $50,000 depending on scope. Full cost breakdown for ADU, bedroom, home office, gym, and rental unit conversions.',
    slug: 'cost-guides/garage-conversion-cost',
    category: 'Cost Guide',
    readTime: '25 min read',
    image: '/images/garageconversion.jpg',
  },
  {
    title: 'EV Charger Installation Guide 2026: Costs, Levels, and Tax Credits',
    description: 'Installing a Level 2 EV charger at home costs $1,000 to $3,500 total. Complete guide to charging levels, electrical requirements, installation costs, and the Section 30C tax credit expiring June 30, 2026.',
    slug: 'guides/ev-charger-installation',
    category: 'Guide',
    readTime: '25 min read',
    image: '/images/EV charging.jpg',
  },
  {
    title: 'Best Garage Cabinets 2026: Steel Systems, Freestanding, and Wall-Mount Picks',
    description: 'The best garage cabinet for most homeowners is a steel freestanding locker in the $200 to $500 range. Compare complete systems, lockers, wall-mount, rolling, and budget picks.',
    slug: 'reviews/best-garage-cabinets',
    category: 'Review',
    readTime: '25 min read',
    image: '/images/garagecabinets.jpg',
      },
  {
      title: 'Best Garage Workbenches 2026: 7 Picks for Every Budget and Project',
      description: 'The best garage workbench for most homeowners is a 48-inch adjustable-height bench with rubberwood top, built-in power, and 2,000 lb capacity. We reviewed 7 top picks.',
      slug: 'reviews/best-garage-workbenches',
      category: 'Review',
      readTime: '25 min read',
      image: '/images/bestworkbenches.jpg',
  },
    {
      title: 'Garage Too Hot in Summer? How to Cool a Garage Ranked by Cost and Effectiveness',
      description: 'An uninsulated garage can reach 10 to 18 degrees hotter than outside. We ranked every cooling method by cost and effectiveness from free fixes to mini-split AC.',
      slug: 'guides/garage-too-hot-in-summer',
      category: 'Guide',
      readTime: '22 min read',
      image: '/images/hotgarage.jpg',
    },
      {
      title: 'Garage Door Won\'t Close? 10 Causes and How to Fix Each One',
      description: 'Your garage door opens fine but won\'t close. Diagnose all 10 causes ranked easiest to hardest — sensors, limits, springs, gears, and more — with fix costs from $0 to $350.',
      slug: 'problems/garage-door-wont-close',
      category: 'Problem',
      readTime: '20 min read',
      image: '/images/garagestuckopen.jpg',
    },
    {
    title: 'Cracked Garage Floor: When to Worry, How to Fix It, and What It Costs',
    description: 'Every concrete garage floor cracks eventually. Learn which cracks are cosmetic vs structural, DIY repair steps, and when to resurface or replace. Fix costs from $5 to $7,000.',
    slug: 'problems/cracked-garage-floor',
    category: 'Problem',
    readTime: '22 min read',
    image: '/images/crackedgarage.jpg',
  },
    {
    title: 'Best Garage Door Keypads 2026: Top Wireless Picks for Every Opener Brand',
    description: 'The best garage door keypads in 2026 cost $25 to $80 and use rolling code security. We review the top 6 keypads for LiftMaster, Chamberlain, Genie, Craftsman, and universal compatibility.',
    slug: 'reviews/best-garage-door-keypads',
    category: 'Review',
    readTime: '20 min read',
    image: '/images/garageopeners.jpg',
  },
  {
    title: 'Garage Door Maintenance: The Complete Annual Checklist',
    description: 'How to maintain your garage door: monthly safety tests, twice-yearly lubrication, annual balance check, and the exact signs that mean call a pro.',
    slug: 'guides/garage-door-maintenance',
    category: 'Guide',
    readTime: '14 min read',
    image: '/images/_garage-door-maintenance.jpg',
  },

    {
    title: 'How to Set Up a Garage Workshop: The Complete Planning Guide',
    description: 'How to set up a garage workshop from scratch. Zone planning, electrical circuits, lighting, workbench placement, flooring, ventilation, and tool storage.',
    slug: 'guides/garage-workshop-setup',
    category: 'Guide',
    readTime: '16 min read',
    image: '/images/garageworkshop.jpg',
  },
  {
    title: 'Garage Floor Oil Stains: How to Remove Them for Good',
    description: 'Remove garage floor oil stains with the right method for your stain\'s age. Fresh spills, set stains, and years-old patches all need different treatment. Step-by-step guide.',
    slug: 'problems/garage-floor-oil-stains',
    category: 'Problem',
    readTime: '12 min read',
    image: '/images/Garage Floor Oil Stain.jpg',
  },

  {
    title: 'Garage Door Won\'t Open: Diagnosis and Fix Guide',
    description: 'Garage door won\'t open? Diagnose the cause in 60 seconds with this symptom-by-symptom guide. Broken springs, dead openers, frozen doors, and more.',
    slug: 'problems/garage-door-wont-open',
    category: 'Problem',
    readTime: '13 min read',
    image: '/images/garagedoorwontopen.jpg',
  },

  {
    title: 'Garage Door Spring Replacement: Cost, Signs, and What to Expect',
    description: 'Garage door spring replacement costs $150 to $350 professionally. Learn the signs your spring is failing, what type you have, and why this is never a DIY repair.',
    slug: 'problems/garage-door-spring-replacement',
    category: 'Problem',
    readTime: '13 min read',
    image: '/images/herogaragespringbroken.jpg',
  },
    {
    title: 'How to Winterize Your Garage: The Complete Fall Checklist',
    description: 'How to winterize your garage before winter. Seals, insulation R-values, lubrication, pipe protection, heater safety, and the full fall checklist.',
    slug: 'guides/how-to-winterize-your-garage',
    category: 'Guide',
    readTime: '13 min read',
    image: '/images/winterizegarage.jpg',
  },
  {
    title: 'The Complete Garage Maintenance Checklist: Every Season, Every System',
    description: 'The complete garage maintenance checklist by season. Every system covered: door, opener, floor, lighting, ventilation, heating, storage, electrical, and security.',
    slug: 'guides/garage-maintenance-checklist',
    category: 'Guide',
    readTime: '15 min read',
    image: '/images/garagemaintence.jpg',
  },
  {
    title: 'How to Paint a Garage Door: A Complete Guide to Prep, Paint, and a Finish That Lasts',
    description: 'How to paint a garage door the right way. Material-specific prep, primer selection, brush vs roller vs sprayer, color and heat warnings, and how long it lasts.',
    slug: 'guides/how-to-paint-a-garage-door',
    category: 'Guide',
    readTime: '14 min read',
    image: '/images/how-to-paint-garage-door.jpg',
  },
  {
    title: 'Garage Door Weather Stripping: When to Replace It and How to Do It Right',
    description: 'Garage door weather stripping replacement guide. Signs it has failed, which of the 4 seals to replace, costs, and step-by-step DIY installation for each type.',
    slug: 'problems/garage-door-weather-stripping',
    category: 'Problem',
    readTime: '12 min read',
    image: '/images/garage-door-weather-stripping.jpg',
  },
  {
    title: 'How to Run Electricity to a Detached Garage: The Complete Planning Guide',
    description: 'How to run electricity to a detached garage. Load calculations, subpanel sizing, underground vs overhead, wire gauge, permits, and what requires a licensed electrician.',
    slug: 'guides/detached-garage-electrical',
    category: 'Guide',
    readTime: '15 min read',
    image: '/images/garage electrical.jpg',
  },
  {
    title: 'Garage Door Off Track: Causes, How to Fix It, and When to Call a Pro',
    description: 'Garage door off track? Diagnose the cause, fix minor derailments safely, and know when to call a pro. Covers bent tracks, broken cables, worn rollers, and repair costs.',
    slug: 'problems/garage-door-off-track',
    category: 'Problem',
    readTime: '12 min read',
    image: '/images/garagetrack.jpg',
  },
  {
    title: 'Garage Door Cable Broke: Causes, What to Do Right Now, and Repair Costs',
    description: 'Garage door cable broke? Find out what caused it, what to do right now, whether you can fix it yourself, and what professional repair costs in 2026.',
    slug: 'problems/garage-door-cable-broke',
    category: 'Problem',
    readTime: '11 min read',
    image: '/images/garagecablebroke.jpg',
  },
  {
    title: 'Garage Door Making Noise? Diagnose the Sound and Fix It',
    description: 'Garage door making noise? Diagnose grinding, squeaking, banging, rattling, and popping sounds by component. Fixes for each noise type and when to call a pro.',
    slug: 'problems/garage-door-makes-noise',
    category: 'Problem',
    readTime: '14 min read',
    image: '/images/garagetrack2.jpg',
  },
  {
    title: 'Garage Insulation Cost 2026: Door, Walls, Ceiling, and Whole Garage Prices',
    description: 'Garage insulation costs $800 to $5,100 for a 2-car garage professionally installed. Garage door insulation kits cost $50 to $200 DIY. Full breakdown by type, surface, and garage size.',
    slug: 'cost-guides/garage-insulation-cost',
    category: 'Cost Guide',
    readTime: '12 min read',
    image: '/images/garage-insulation.jpg',
  },
  {
    title: 'NEMA 14-50 Outlet Installation Cost 2026: Garage EV Charging Circuit Prices',
    description: 'NEMA 14-50 outlet installation costs $300 to $1,000 for most garages in 2026. Covers outlet types, wire run length, panel upgrade costs, permits, and NEMA 14-50 vs 6-50 vs hardwired.',
    slug: 'cost-guides/nema-14-50-outlet-installation-cost',
    category: 'Cost Guide',
    readTime: '11 min read',
    image: '/images/NEMA 14-50.jpg',
  },
]

export function searchArticles(query: string): Article[] {
  if (!query.trim()) return []
  const terms = query.toLowerCase().split(/\s+/)
  return articles.filter((article) => {
    const searchText = `${article.title} ${article.description} ${article.category}`.toLowerCase()
    return terms.every((term) => searchText.includes(term))
  })
}